AMUSE_DIR?=../../../../..
-include ${AMUSE_DIR}/config.mk

all: lib/estars.jar

RM ?= rm
JAVAC ?= javac
JAR ?= jar

lib/estars.jar: $(shell find src)
	@echo Compiling Amuse/Ibis lib
	$(RM) -r tmp dist
	mkdir tmp
	mkdir dist
	$(JAVAC) -g -classpath "lib/*:lib/jogl/*"  -d tmp $(shell find src -name *.java)

	@echo Building jar file
	$(JAR) -cf dist/asterisk.jar -C tmp .
	$(JAR) -uf dist/asterisk.jar images shaders
	$(RM) -r tmp
	@echo done compiling Stars lib

clean:
	$(RM) -r tmp dist


