/*
 * Copyright 2013 Netherlands eScience Center
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package nl.esciencecenter.amuse.distributed;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Class that holds configuration information for a Amuse installation. Loaded from the config.mk file generated by AMUSE
 * 
 * @author Niels Drost
 */
public class AmuseConfiguration {

    File amuseHome;
    
    Map<String, String> config;

    public AmuseConfiguration(File amuseHome) throws FileNotFoundException, IOException, DistributedAmuseException {
        this.amuseHome = amuseHome;
        
        config = new HashMap<String, String>();
        
        File configFile = new File(amuseHome, "config.mk");

        try (BufferedReader reader = new BufferedReader(new FileReader(configFile))) {
            while (true) {
                String line = reader.readLine();

                if (line == null) {
                    return;
                } else if (line.trim().isEmpty() || line.startsWith("#") || line.startsWith("export")) {
                    //SKIP
                } else {
                    String[] elements = line.split("=", 2);

                    if (elements.length != 2) {
                        throw new DistributedAmuseException("Could not parse config option \"" + line + "\"");
                    }

                    String option = elements[0].trim();
                    String value = elements[1].trim();

                    config.put(option, value);

                }
            }
        }
    }

    String getConfigOption(String name) throws DistributedAmuseException {
        String result = config.get(name);

        if (result == null) {
            throw new DistributedAmuseException("configuration option not found: \"" + name + "\"");
        }

        return result;
    }

    public File getAmuseHome() {
        return amuseHome;
    }

    /**
     * @return
     */
    public boolean isMpiexecEnabled() {
        // TODO Auto-generated method stub
        return false;
    }

    /**
     * @return
     */
    public String getMpiexec() {
        // TODO Auto-generated method stub
        return null;
    }
}
